### PR TITLE
Swipe component should accept valid React children

### PR DESCRIPTION
**Pull request by LBRDan**
A simple Typescript for Swipe component
As far as I can see, it should be able to accept any valid React Children

Repro case [HERE](https://stackblitz.com/edit/react-ts-rlp8eu?file=App.tsx)

### CODE REVIEW

**Comment by LBRDan** [comment]
Hi @leandrowd, Is there something wrong about this PR?

**Comment by patotoma** [comment]
I'm using this as a workaround until this is merged:

Create file `react-easy-swipe.d.ts` in project root with:

```
import React from "react";
import "react-easy-swipe";

declare module "react-easy-swipe" {
  interface SwipeProps {
    // workaround for https://github.com/leandrowd/react-easy-swipe/pull/64
    children?: React.ReactNode;
  }
}
```

**Comment by mlshv** [comment]
This should definitely be merged and released :-)

**Comment by leandrowd** [comment]
Sorry for the delay. I'm not actively maintaining this package. I just merged another PR that solves this problem and published it to npm.

**Pull request closed without merging**
